package symphony.apt.model;

public enum TypeClassification {
  DEFAULT_OR_PRIMITIVE_TYPE,
  CUSTOM_OBJECT_TYPE,
  COLLECTION_PARAMETERIZED_TYPE,
  MAP_PARAMETERIZED_TYPE,
  FUNCTION_PARAMETERIZED_TYPE,
  SUPPLIER_PARAMETERIZED_TYPE,
}
