addSbtPlugin("org.scoverage"      % "sbt-scoverage"      % "2.0.12")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"       % "2.5.2")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"     % "1.9.3")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"            % "0.4.7")
addSbtPlugin("com.lightbend.sbt"  % "sbt-java-formatter" % "0.8.0")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"           % "2.5.4")
addSbtPlugin("com.github.sbt"     % "sbt-jacoco"         % "3.5.0")
